name: ROMA-tutorial
channels:
  - default
  - conda-forge

dependencies:
  - python=3.9.11
  - pip=24.0
  - pip:
    - xlrd==2.0.1
    - numpy==1.26.4
    - matplotlib==3.9.0
    - scipy==1.13.0
    - openpyxl==3.1.2